#!/bin/bash

# This script automates ssh connection using nmap. It is appropriate when a pi
# is on a a network other than the one generated by the Telstra 4G USB Modem.
# (SSID MHP_MobileNet). It can be used when connecting a pi to a personal
# hotspot or any other type of WiFi. It won't work with Monash's Free WiFi
# because it requires an "I agree" clause.

# MAC Address
MAC=B8:27:EB

# Obtain local net id. For me this is 10.1.1.0
NET=$(ip route get 8.8.8.8 | awk '{print $NF; exit}')

# Use local net ID to find raspberry pi on local network using MAC Address. Loop here until pi is online.
while [ -z "$temp" ];
do
temp=$(sudo nmap -sP $NET/24 | awk '/^Nmap/{ip=$NF}/$MAC/{print ip}')
done

# Remove parathensis from temp output
new_temp=$(echo $temp|sed 's/(//g')
PI_IP=$(echo $new_temp|sed 's/)//g')

# Define pi username
USERNAME=pi

# Begin ssh session
ssh ${USERNAME}@${PI_IP}
