function [fitresult, gof] = createFitSlope(Dist, Height,Plot)
%CREATEFIT(DIST,HEIGHT)
%  Create a fit.
%
%  Data for 'HeightFit' fit:
%      X Input : Dist
%      Y Output: Height
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Nov-2017 15:58:24


%% Fit: 'HeightFit'.
[xData, yData] = prepareCurveData( Dist, Height );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 1.5e-05;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

if Plot == 0
    % Plot fit with data.
    figure( 'Name', 'HeightFit' );
    h = plot( fitresult, xData, yData );
    legend( h, 'Height vs. Dist', 'HeightFit', 'Location', 'NorthEast' );
    % Label axes
    xlabel Dist
    ylabel Height
    grid on
else
end

